apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: weather-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: weather-app
