name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  release:
    types: [published]
v1.0.3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from Git tag
        id: get_version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Set version for push
        id: set_version
        run: |
          if [ -z "$VERSION" ]; then
            VERSION=latest
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          export VERSION

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/weather-app:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/weather-app:latest
        outputs:
          built_version: ${{ steps.build-and-push.outputs.TAG }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true # Prevents using the token for pushes

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Deployment Manifest
        uses: update-k8s-image@v2
        with:
          manifest-path: deployment.yaml
          image-name: ${{ secrets.DOCKERHUB_USERNAME }}/weather-app
          image-tag: ${{ needs.build-and_push.outputs.built_version }}
          namespace: default
          context: .
